#!/usr/bin/env node
/**
 * Cross-Platform AI Workspace Sync Engine
 *
 * Links (or copies) canonical sources in .ai/ to the locations
 * consumed by Claude Code, VS Code Copilot, Gemini CLI, and others.
 *
 * Run: node .ai/scripts/sync.js
 * Watch: node .ai/scripts/sync.js --watch
 * Zero external dependencies. Works identically on macOS and Windows.
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// Always operate from the repo root (script lives at .ai/scripts/sync.js)
const ROOT = path.resolve(__dirname, "../..");
process.chdir(ROOT);

const MANIFEST_PATH = path.join(__dirname, "..", ".sync-manifest.json");
const WATCH_MODE = process.argv.includes("--watch");

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const dirsToCreate = [".claude/commands", ".claude/skills", ".github/prompts", ".github/skills"];

// Single source -> single destination
const fileLinks = [
  { src: ".ai/mcp-servers.json", dest: ".mcp.json" },
];

// Multiple sources concatenated -> every harness (project-specific first, base second)
const compositeLinks = {
  sources: [".ai/project.md", ".ai/base.md"],
  dests: ["AGENTS.md", "CLAUDE.md", "GEMINI.md", ".github/copilot-instructions.md"],
};

// Skills: flat .ai/skills/<name>.md -> <target>/<name>/SKILL.md
const skillTargets = [".claude/skills", ".github/skills"];

// Prompts: .ai/prompts/<name>.md -> slash commands in each harness
const promptTargets = [
  { root: ".claude/commands", suffix: ".md" },
  { root: ".github/prompts", suffix: ".prompt.md" },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sha256(filePath) {
  return crypto.createHash("sha256").update(fs.readFileSync(filePath)).digest("hex");
}

function loadManifest() {
  try {
    return JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8"));
  } catch {
    return {};
  }
}

const manifest = loadManifest();

/**
 * Link src -> dest. Symlink where permitted; copy fallback with drift detection.
 * Guardrails:
 *  - Existing symlinks are regenerated (always ours).
 *  - Existing physical files matching the manifest hash are stale copies -> refreshed.
 *  - Any other physical file is a human-made local override -> preserved untouched.
 */
function syncAsset(src, dest) {
  const stats = fs.lstatSync(dest, { throwIfNoEntry: false });
  if (stats) {
    if (stats.isSymbolicLink()) {
      fs.unlinkSync(dest);
    } else if (manifest[dest] && manifest[dest] === sha256(dest)) {
      fs.unlinkSync(dest); // stale generated copy — safe to refresh
    } else {
      console.log(`  \x1b[33m!\x1b[0m Local override at ${dest} — preserving.`);
      return;
    }
  }

  try {
    const relTarget = path.relative(path.dirname(path.resolve(dest)), path.resolve(src));
    fs.symlinkSync(relTarget, path.resolve(dest), "file");
    delete manifest[dest];
    console.log(`  \x1b[32m✓\x1b[0m Linked: ${dest} -> ${src}`);
  } catch (err) {
    if (err.code === "EPERM" || err.code === "EACCES" || err.code === "EINVAL") {
      // Copy fallback — inject header warning into .md files
      if (dest.endsWith(".md")) {
        const header = `<!-- AUTO-GENERATED by .ai/scripts/sync.js — edit the source at ${src} instead -->\n`;
        const content = fs.readFileSync(src, "utf8");
        fs.writeFileSync(dest, header + content, "utf8");
      } else {
        fs.copyFileSync(src, dest);
      }
      manifest[dest] = sha256(dest);
      console.log(`  \x1b[32m→\x1b[0m Copied (no symlink permission): ${dest}`);
    } else {
      console.error(`  \x1b[31m✕\x1b[0m Error linking ${dest}:`, err.message);
    }
  }
}

/**
 * Remove symlinks in a directory that we no longer generate.
 */
function cleanStaleLinks(dir, expectedFiles) {
  if (!fs.existsSync(dir)) return;
  const expected = new Set(expectedFiles);
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isSymbolicLink() && !expected.has(entry.name)) {
      fs.unlinkSync(full);
      console.log(`  \x1b[90m✗\x1b[0m Removed stale: ${full}`);
    } else if (!entry.isSymbolicLink() && !entry.isDirectory() && !expected.has(entry.name)) {
      // Stale generated copy — only remove if we originally wrote it
      if (manifest[full] && manifest[full] === sha256(full)) {
        fs.unlinkSync(full);
        delete manifest[full];
        console.log(`  \x1b[90m✗\x1b[0m Removed stale copy: ${full}`);
      }
    } else if (entry.isDirectory()) {
      // For skill folders: check if the SKILL.md inside is stale
      const skillFile = path.join(full, "SKILL.md");
      const skillStats = fs.lstatSync(skillFile, { throwIfNoEntry: false });
      if (!expected.has(entry.name)) {
        if (skillStats?.isSymbolicLink()) {
          fs.unlinkSync(skillFile);
          fs.rmdirSync(full);
          console.log(`  \x1b[90m✗\x1b[0m Removed stale: ${full}/`);
        } else if (skillStats && manifest[skillFile] && manifest[skillFile] === sha256(skillFile)) {
          fs.unlinkSync(skillFile);
          delete manifest[skillFile];
          fs.rmdirSync(full);
          console.log(`  \x1b[90m✗\x1b[0m Removed stale copy: ${full}/`);
        }
      }
    }
  }
}

const AI_SYNC_MARKER = "<!-- ai-sync-generated -->";

/**
 * Concatenate multiple source files and write to each destination.
 * Ownership is detected via an embedded marker comment at the end of each
 * generated file — no external manifest needed.
 * Guardrails:
 *  - Existing symlinks are always replaced (always ours).
 *  - Files containing the marker are our generated copies → refreshed.
 *  - Any other physical file is a human-made local override → preserved.
 */
function writeComposite(sources, dests) {
  const parts = sources
    .filter((src) => {
      if (!fs.existsSync(src)) {
        console.log(`  \x1b[33m!\x1b[0m Source missing: ${src} — skipping.`);
        return false;
      }
      return true;
    })
    .map((src) => fs.readFileSync(src, "utf8").trimEnd());

  if (parts.length === 0) return;

  const content = parts.join("\n\n") + "\n\n" + AI_SYNC_MARKER + "\n";

  dests.forEach((dest) => {
    const stats = fs.lstatSync(dest, { throwIfNoEntry: false });
    if (stats) {
      if (stats.isSymbolicLink()) {
        fs.unlinkSync(dest);
      } else {
        const existing = fs.readFileSync(dest, "utf8");
        if (existing === content) {
          console.log(`  \x1b[90m–\x1b[0m Unchanged: ${dest}`);
          return;
        }
        if (!existing.includes(AI_SYNC_MARKER)) {
          console.log(`  \x1b[33m!\x1b[0m Local override at ${dest} — preserving.`);
          return;
        }
      }
    }
    fs.writeFileSync(dest, content, "utf8");
    console.log(`  \x1b[32m→\x1b[0m Composed: ${dest}`);
  });
}

// ---------------------------------------------------------------------------
// Execution
// ---------------------------------------------------------------------------

function runSync() {
  console.log("\x1b[34m=== Syncing Cross-Platform AI Workspace ===\x1b[0m\n");

  console.log("\x1b[34m[1/5] Ensuring directories exist...\x1b[0m");
  dirsToCreate.forEach((dir) => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      console.log(`  ✓ Created: ${dir}`);
    }
  });

  console.log("\x1b[34m\n[2/5] Generating root + harness linkages...\x1b[0m");
  fileLinks.forEach((link) => {
    if (fs.existsSync(link.src)) {
      syncAsset(link.src, link.dest);
    } else {
      console.log(`  \x1b[33m!\x1b[0m Source missing: ${link.src} — skipping.`);
    }
  });
  writeComposite(compositeLinks.sources, compositeLinks.dests);

  console.log("\x1b[34m\n[3/5] Compiling skills for Claude Code + Copilot...\x1b[0m");
  const skillSources = fs.existsSync(".ai/skills")
    ? fs.readdirSync(".ai/skills", { withFileTypes: true }).filter((item) => item.isFile() && item.name.endsWith(".md"))
    : [];

  const skillNames = skillSources.map((item) => path.basename(item.name, ".md"));

  skillTargets.forEach((targetRoot) => {
    cleanStaleLinks(targetRoot, skillNames);
    skillSources.forEach((item) => {
      const skillName = path.basename(item.name, ".md");
      const src = path.join(".ai/skills", item.name);
      const skillDir = path.join(targetRoot, skillName);
      fs.mkdirSync(skillDir, { recursive: true });
      syncAsset(src, path.join(skillDir, "SKILL.md"));
    });
  });

  console.log("\x1b[34m\n[4/5] Compiling prompts / slash commands...\x1b[0m");
  const promptSources = fs.existsSync(".ai/prompts")
    ? fs
        .readdirSync(".ai/prompts", { withFileTypes: true })
        .filter((item) => item.isFile() && item.name.endsWith(".md"))
    : [];

  promptTargets.forEach(({ root, suffix }) => {
    const expectedNames = promptSources.map((item) => path.basename(item.name, ".md") + suffix);
    cleanStaleLinks(root, expectedNames);
    promptSources.forEach((item) => {
      const promptName = path.basename(item.name, ".md");
      const src = path.join(".ai/prompts", item.name);
      syncAsset(src, path.join(root, promptName + suffix));
    });
  });

  console.log("\x1b[34m\n[5/5] Saving manifest...\x1b[0m");
  const newManifestJson = JSON.stringify(manifest, null, 2);
  const existingManifestJson = (() => { try { return fs.readFileSync(MANIFEST_PATH, "utf8"); } catch { return null; } })();
  if (newManifestJson !== existingManifestJson) {
    fs.writeFileSync(MANIFEST_PATH, newManifestJson);
    console.log("  ✓ Manifest updated.");
  } else {
    console.log("  – Manifest unchanged.");
  }
  console.log("\x1b[32m\n=== Workspace Synchronized ===\x1b[0m");
}

// ---------------------------------------------------------------------------
// Watch Mode
// ---------------------------------------------------------------------------

function startWatch() {
  const DEBOUNCE_MS = 300;
  let timeout = null;

  const debouncedSync = () => {
    if (timeout) clearTimeout(timeout);
    timeout = setTimeout(() => {
      console.log(`\n\x1b[90m[${new Date().toLocaleTimeString()}] Change detected in .ai/ — re-syncing...\x1b[0m\n`);
      runSync();
    }, DEBOUNCE_MS);
  };

  // Watch .ai/ recursively (supported on macOS and Windows)
  fs.watch(path.join(ROOT, ".ai"), { recursive: true }, (eventType, filename) => {
    // Ignore manifest and hidden files
    if (!filename || filename.startsWith(".sync-manifest") || filename.startsWith(".")) return;
    debouncedSync();
  });

  console.log("\x1b[36m\n👁  Watching .ai/ for changes (Ctrl+C to stop)...\x1b[0m\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

runSync();

if (WATCH_MODE) {
  startWatch();
}
