from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, Union


class Dependency:
	def __init__(self, val: Any = None) -> None:
		self.val: Any = val

	def modified(self) -> None: ...


class Color:
	def __init__(self, rgba: Sequence[float] = (0, 0, 0, 1)) -> None:
		self.r: float = rgba[0]
		self.g: float = rgba[1]
		self.b: float = rgba[2]
		self.a: float = rgba[3]

	def __iter__(self): ...
	def __getitem__(self, index: int) -> float: ...
	def __setitem__(self, index: int, value: float) -> None: ...


class Vector:
	def __init__(self, x: float = 0, y: float = 0, z: float = 0) -> None:
		self.x: float = x
		self.y: float = y
		self.z: float = z

	def __iter__(self): ...
	def __getitem__(self, index: int) -> float: ...
	def __setitem__(self, index: int, value: float) -> None: ...
	def __add__(self, other: 'Vector') -> 'Vector': ...
	def __sub__(self, other: 'Vector') -> 'Vector': ...
	def __mul__(self, other: Union['Vector', float]) -> 'Vector': ...
	def length(self) -> float: ...
	def normalize(self) -> 'Vector': ...
	def dot(self, other: 'Vector') -> float: ...
	def cross(self, other: 'Vector') -> 'Vector': ...
	def copy(self) -> 'Vector': ...


class Position:
	def __init__(self, x: float = 0, y: float = 0, z: float = 0) -> None:
		self.x: float = x
		self.y: float = y
		self.z: float = z

	def __iter__(self): ...
	def __getitem__(self, index: int) -> float: ...
	def __setitem__(self, index: int, value: float) -> None: ...
	def copy(self) -> 'Position': ...


class Matrix:
	def __init__(self, *args) -> None: ...
	def __getitem__(self, index: int) -> float: ...
	def __setitem__(self, index: int, value: float) -> None: ...
	def __mul__(self, other: Union['Matrix', Vector, Position]) -> Any: ...
	def copy(self) -> 'Matrix': ...
	def transpose(self) -> 'Matrix': ...
	def invert(self) -> 'Matrix': ...
	def determinant(self) -> float: ...
	def translate(self, x: float, y: float, z: float) -> None: ...
	def rotate(self, x: float, y: float, z: float, pivot: Optional[Position] = None) -> None: ...
	def scale(self, x: float, y: float, z: float) -> None: ...
	def identity(self) -> None: ...


class Quaternion:
	def __init__(self, x: float = 0, y: float = 0, z: float = 0, w: float = 1) -> None:
		self.x: float = x
		self.y: float = y
		self.z: float = z
		self.w: float = w

	def __iter__(self): ...
	def __getitem__(self, index: int) -> float: ...
	def __mul__(self, other: 'Quaternion') -> 'Quaternion': ...
	def copy(self) -> 'Quaternion': ...
	def normalize(self) -> 'Quaternion': ...
	def slerp(self, other: 'Quaternion', t: float) -> 'Quaternion': ...


class FileInfo:
	def __init__(self, path: str) -> None:
		self.path: str = path
		self.ext: str = ''
		self.fileType: str = ''
		self.absPath: str = ''
		self.dir: str = ''
		self.exists: bool = False
		self.isDir: bool = False
		self.isFile: bool = False
		self.baseName: str = ''


class ArcBall:
	def __init__(self) -> None: ...
	def beginRotate(self, x: float, y: float) -> None: ...
	def rotate(self, x: float, y: float) -> Quaternion: ...


class Camera:
	def __init__(self) -> None: ...


class Timecode:
	def __init__(self, *args) -> None: ...
	def __str__(self) -> str: ...


class MenuObject:
	def __init__(self, menuNames: List[str], menuLabels: Optional[List[str]] = None) -> None:
		self.menuNames: List[str] = menuNames
		self.menuLabels: List[str] = menuLabels or menuNames


# Module-level attributes
fileTypes: Dict[str, List[str]] = {}


# Module-level functions
def rand(seed: Union[int, float]) -> float: ...
def clamp(inputVal: Union[int, float], min: Union[int, float], max: Union[int, float]) -> Union[int, float]: ...
def remap(inputVal: float, fromMin: float, fromMax: float, toMin: float, toMax: float) -> float: ...
def base(s: str) -> str: ...
def digits(s: str) -> Optional[int]: ...
def validName(s: str) -> str: ...
def validPath(s: str) -> str: ...
def expand(pattern: str) -> List[Any]: ...
def expandPath(path: str) -> str: ...
def collapsePath(path: str, asExpression: bool = False) -> str: ...
def split(string: str, eval: bool = False) -> List[str]: ...
def match(pattern: str, inputList: List[Any], caseSensitive: bool = True) -> List[Any]: ...
def forceCrash() -> None: ...
def tryExcept(func1: Callable, func2val: Any) -> Any: ...
def ParMenu(menuNames: List[str], menuLabels: Optional[List[str]] = None) -> MenuObject: ...
def TableMenu(table: Any, nameCol: int = 0, labelCol: Optional[int] = None, includeFirstRow: bool = False) -> MenuObject: ...
def isPointCloudFile(path: str) -> bool: ...
def parSummary(OPType: Any) -> Dict[str, Any]: ...
